version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Mizdooni
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql


  backend:
    image: mhaghili/ca8-backend:latest
    container_name: backend-container
    ports:
      - "8093:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/Mizdooni
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql

  frontend:
    image: mhaghili/ca8-frontend:latest
    container_name: frontend-container
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql-data: